server:
  port: 9091
  context-path: /api

spring:
  application:
    name: wutong-payment
  dubbo:
    scan: com.wutong
    registry:
      address: zookeeper://127.0.0.1:2181
    application:
      name: wutong-payment
    module:
      default: false
  session:
    store-type: redis
  redis:
    host: 192.168.3.189
    port: 6379
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  http: # 开启encodingFilter，设置字符集
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart: # 文件上传限制
      max-file-size: 100KB
      max-request-size: 1MB
  devtools:
    restart:
      enabled: false

logging:
  level:
    root: debug
    
weixin: 
  app-id: wx3016335d2d4d60c6
  mch-id: 1493205162
  mch-key: 329E8AA366CFC70F93747A74D8EB1BA6
  notify-url: http://aimeryaya.oicp.io:21593/api/wxpay/callback
  trade-type: NATIVE
  


